export const EDITOR_SET_CTX = 'EDITOR_SET_CTX'
export const EDITOR_SET_ALPHA_PATTERN = 'EDITOR_SET_ALPHA_PATTERN'

export const SOURCE_SET_IMAGE = 'SOURCE_SET_IMAGE'
export const SOURCE_SET_PROPS = 'SOURCE_SET_PROPS'

export const BUILD_SETTINGS_SET = 'BUILD_SETTINGS_SET'

export const TOOL_PATH_SET_GENERATOR = 'TOOL_PATH_SET_GENERATOR'